export const birthData = [
  {
    "moon_phase" : "Crescent Moon",
    "moon_phase_description" : "Born under this phase, your life will be defined by your ability to take risks and break through the confines that would otherwise hold you back. Engaging with a struggle that feels important for you will be key to feeling successful. This might be something you felt from birth; a sense that you need to push away from what is familiar and move towards what is unknown.",
    "planets" : [
      "{\"name\":\"Sun\",\"full_degree\":271.1902,\"norm_degree\":1.1902,\"speed\":1.0189,\"is_retro\":\"false\",\"sign_id\":10,\"sign\":\"Capricorn\",\"house\":1,\"interpretation\":\"Your Sun (your identity) is in Capricorn (disciplined and self-restricting style) in the 1st house (of one's self, body, appearance and vitality).\",\"special\":[]}",
      "{\"name\":\"Moon\",\"full_degree\":327.2542,\"norm_degree\":27.2542,\"speed\":14.2271,\"is_retro\":\"false\",\"sign_id\":11,\"sign\":\"Aquarius\",\"house\":2,\"interpretation\":\"Your Moon (your body) is in Aquarius (intellectual and definitive style) in the 2nd house (of one's assets, resources, and livelihood).\",\"special\":[]}",
      "{\"name\":\"Mars\",\"full_degree\":162.2012,\"norm_degree\":12.2012,\"speed\":0.2485,\"is_retro\":\"false\",\"sign_id\":6,\"sign\":\"Virgo\",\"house\":9,\"interpretation\":\"Mars (how you take action) is in Virgo (perfecting and analytical style) in the 9th house (of travel, education, publishing, religion, astrology and philosophy).\",\"special\":[]}",
      "{\"name\":\"Mercury\",\"full_degree\":255.4004,\"norm_degree\":15.4004,\"speed\":1.4705,\"is_retro\":\"false\",\"sign_id\":9,\"sign\":\"Sagittarius\",\"house\":12,\"interpretation\":\"Mercury (how you communicate) is in Sagittarius (buoyant and positive style) in the 12th house (of hidden life, secrets, sorrow and loss).\",\"special\":[\"is in its detriment.\"]}",
      "{\"name\":\"Jupiter\",\"full_degree\":160.2302,\"norm_degree\":10.2302,\"speed\":0.0097,\"is_retro\":\"false\",\"sign_id\":6,\"sign\":\"Virgo\",\"house\":9,\"interpretation\":\"Jupiter (how you create abundance) is in Virgo (perfecting and analytical style) in the 9th house (of travel, education, publishing, religion, astrology and philosophy).\",\"special\":[\"is in its detriment.\"]}",
      "{\"name\":\"Venus\",\"full_degree\":301.0634,\"norm_degree\":1.0634,\"speed\":1.2372,\"is_retro\":\"false\",\"sign_id\":11,\"sign\":\"Aquarius\",\"house\":2,\"interpretation\":\"Venus (how you connect) is in Aquarius (intellectual and definitive style) in the 2nd house (of one's assets, resources, and livelihood).\",\"special\":[]}",
      "{\"name\":\"Saturn\",\"full_degree\":176.8326,\"norm_degree\":26.8326,\"speed\":0.026,\"is_retro\":\"false\",\"sign_id\":6,\"sign\":\"Virgo\",\"house\":9,\"interpretation\":\"Saturn (how and where you create boundaries) is in Virgo (perfecting and analytical style) in the 9th house (of travel, education, publishing, religion, astrology and philosophy).\",\"special\":[]}",
      "{\"name\":\"Uranus\",\"full_degree\":233.6264,\"norm_degree\":23.6264,\"speed\":0.0525,\"is_retro\":\"false\",\"sign_id\":8,\"sign\":\"Scorpio\",\"house\":11,\"interpretation\":\"Uranus (how and where you innovate and disrupt) is in Scorpio (mysterious and penetrating style) in the 11th house (of friends, community, patrons, and good fortune).\",\"special\":[]}",
      "{\"name\":\"Neptune\",\"full_degree\":260.6151,\"norm_degree\":20.6151,\"speed\":0.0373,\"is_retro\":\"false\",\"sign_id\":9,\"sign\":\"Sagittarius\",\"house\":12,\"interpretation\":\"Neptune (how you use your imagination and transcend boundaries) is in Sagittarius (buoyant and positive style) in the 12th house (of hidden life, secrets, sorrow and loss).\",\"special\":[]}",
      "{\"name\":\"Pluto\",\"full_degree\":201.4697,\"norm_degree\":21.4697,\"speed\":0.0188,\"is_retro\":\"false\",\"sign_id\":7,\"sign\":\"Libra\",\"house\":10,\"interpretation\":\"Pluto (how you transform) is in Libra (accommodating and justice-oriented style) in the 10th house (of career and public roles).\",\"special\":[]}",
      "{\"name\":\"Node\",\"full_degree\":150.9982,\"norm_degree\":0.9982,\"speed\":-0.0067,\"is_retro\":\"true\",\"sign_id\":6,\"sign\":\"Virgo\",\"house\":9,\"interpretation\":\"Node (hunger for worldly success, attaining material comfort, and the desire to achieve) is in Virgo (perfecting and analytical style) in the 9th house (of travel, education, publishing, religion, astrology and philosophy).\",\"special\":[]}",
      "{\"name\":\"Chiron\",\"full_degree\":39.4837,\"norm_degree\":9.4837,\"speed\":-0.0259,\"is_retro\":\"true\",\"sign_id\":2,\"sign\":\"Taurus\",\"house\":5,\"interpretation\":\"Chiron (the wounds that push you to seek healing, what and how you teach as well as the teachers in your life) is in Taurus (grounded and stabilizing style) in the 5th house (of children, creative projects, sex, and pleasure).\",\"special\":[]}",
      "{\"name\":\"Part of Fortune\",\"full_degree\":240.9329,\"norm_degree\":0.9329,\"speed\":0,\"is_retro\":\"false\",\"sign_id\":9,\"sign\":\"Sagittarius\",\"house\":12,\"interpretation\":\"Part of Fortune (an Arabic calculation that indicates where you might find luck) is in Sagittarius (buoyant and positive style) in the 12th house (of hidden life, secrets, sorrow and loss).\",\"special\":[]}"
    ],
    "houses" : [
      "{\"house\":1,\"sign\":\"Capricorn\",\"degree\":270}",
      "{\"house\":2,\"sign\":\"Aquarius\",\"degree\":300}",
      "{\"house\":3,\"sign\":\"Pisces\",\"degree\":330}",
      "{\"house\":4,\"sign\":\"Aries\",\"degree\":0}",
      "{\"house\":5,\"sign\":\"Taurus\",\"degree\":30}",
      "{\"house\":6,\"sign\":\"Gemini\",\"degree\":60}",
      "{\"house\":7,\"sign\":\"Cancer\",\"degree\":90}",
      "{\"house\":8,\"sign\":\"Leo\",\"degree\":120}",
      "{\"house\":9,\"sign\":\"Virgo\",\"degree\":150}",
      "{\"house\":10,\"sign\":\"Libra\",\"degree\":180}",
      "{\"house\":11,\"sign\":\"Scorpio\",\"degree\":210}",
      "{\"house\":12,\"sign\":\"Sagittarius\",\"degree\":240}"
    ],
    "light_leader" : "Sun",
    "rising_sign" : "{\"Capricorn\"}",
    "aspects" : [
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Mars\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Jupiter\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Saturn\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Uranus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Pluto\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Sun\",\"aspected_planet\":\"Ascendant\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Moon\",\"aspected_planet\":\"Mercury\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Moon\",\"aspected_planet\":\"Venus\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Moon\",\"aspected_planet\":\"Uranus\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Moon\",\"aspected_planet\":\"Neptune\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Moon\",\"aspected_planet\":\"Pluto\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Sun\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Mercury\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Jupiter\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Saturn\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Uranus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Neptune\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Mars\",\"aspected_planet\":\"Ascendant\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Moon\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Mars\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Jupiter\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Venus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Saturn\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Neptune\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Mercury\",\"aspected_planet\":\"Pluto\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Sun\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Mars\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Mercury\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Saturn\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Uranus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Neptune\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Jupiter\",\"aspected_planet\":\"Ascendant\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Venus\",\"aspected_planet\":\"Moon\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Venus\",\"aspected_planet\":\"Mercury\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Venus\",\"aspected_planet\":\"Uranus\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Venus\",\"aspected_planet\":\"Neptune\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Venus\",\"aspected_planet\":\"Pluto\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Sun\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Mars\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Mercury\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Jupiter\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Uranus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Neptune\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Saturn\",\"aspected_planet\":\"Ascendant\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Sun\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Moon\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Mars\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Jupiter\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Venus\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Saturn\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Uranus\",\"aspected_planet\":\"Ascendant\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Moon\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Mars\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Mercury\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Jupiter\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Venus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Saturn\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Neptune\",\"aspected_planet\":\"Pluto\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Sun\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Moon\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Mercury\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Venus\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Neptune\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Pluto\",\"aspected_planet\":\"Ascendant\",\"type\":\"Square\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Sun\",\"type\":\"Conjunction\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Mars\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Jupiter\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Saturn\",\"type\":\"Trine\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Uranus\",\"type\":\"Sextile\"}",
      "{\"aspecting_planet\":\"Ascendant\",\"aspected_planet\":\"Pluto\",\"type\":\"Square\"}"
    ],
  }
]